---
- name: Docker | Add Docker apt-key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker.asc
    mode: "0644"
  become: true
  tags:
    - docker
    - setup

- name: Docker | Add Docker apt-repository
  ansible.builtin.apt_repository:
    repo: "deb {{ signature }} https://download.docker.com/linux/{{ distribution }} {{ release }} stable"
    state: present
    update_cache: true
  become: true
  vars:
    signature: "[arch=amd64 signed-by=/usr/share/keyrings/docker.asc]"
    distribution: "{{ ansible_distribution | lower }}"
    release: "{{ ansible_distribution_release | lower }}"
  tags:
    - docker
    - setup

- name: Docker | Ensure dependencies are present
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - python3-pip
    state: present
  become: true
  tags:
    - docker
    - setup

- name: Docker | Ensure Docker is installed
  when: not ansible_check_mode
  ansible.builtin.apt:
    name:
      - docker-ce
    state: present
    update_cache: true
  become: true
  tags:
    - docker
    - setup

- name: Docker | Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Docker | Add user {{ ansible_user }} to group docker for fix permissions
  command: sudo usermod -aG docker ${USER}
  become: true
  

- name: Docker | Ensure python modules are installed
  when: not ansible_check_mode
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
  become: true
  tags:
    - docker
    - setup

- name: Docker | Ensure Docker is started
  when: not ansible_check_mode
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  tags:
    - docker
    - service
